# /server/dockerfile-develop
FROM python:3.10

RUN apt-get -y update
RUN apt-get -y install vim

RUN mkdir /server
ADD * /server

WORKDIR /server

RUN pip install --upgrade pip

RUN pip install -r ./requirements.txt

EXPOSE 8000
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi.develop:application"]